version: "3"
services: 
  app:
    environment:
      - IS_PROD=1
    container_name: shopee-backend
    restart: always
    build: .
    ports:
      - '3000:3000'
  mysql56:
    container_name: shopee-mysql
    image: mysql:5.6
    ports:
      - '33060:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret