CREATE DATABASE IF NOT EXISTS `shopee_tes_db` /*!40100 DEFAULT CHARACTER SET latin1 */;



USE `shopee_tes_db`;


CREATE TABLE IF NOT EXISTS `SH_ITEMS` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_NAME` varchar(45) NOT NULL,
  `ITEM_TAX_CODE` int(11) DEFAULT NULL,
  `ITEM_PRICE` int(11) DEFAULT NULL,
  `CREATED_ON` datetime DEFAULT NULL,
  `UPDATED_ON` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ITEM_NAME_UNIQUE` (`ITEM_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


INSERT INTO `SH_ITEMS` VALUES (1,'Lucky Stretch',2,1000,NULL,NULL),(2,'Big Mac',1,1000,NULL,NULL),(3,'Movie',3,150,NULL,NULL);